CREATE TABLE organizations
(
    id SERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    prescribed_working_hours FLOAT
    -- created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)