CREATE TABLE users
(
    id SERIAL PRIMARY KEY,
    uid VARCHAR(64) NOT NULL,
    family_name VARCHAR(64) NOT NULL,
    given_name VARCHAR(64) NOT NULL,
    email VARCHAR(64) NOT NULL,
    password VARCHAR(64) NOT NULL,
      
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)